name: Continuous Deployment

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      # Build and push the Docker image
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/tehpicix/stasispearl:latest
            ghcr.io/tehpicix/stasispearl:${{ github.sha }}
